# Generated by Django 5.1.1 on 2024-11-08 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskfile',
            name='org',
        ),
        migrations.AddField(
            model_name='taskfile',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.task'),
        ),
    ]
