# Generated by Django 5.1.1 on 2024-11-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='org_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
