# Generated by Django 5.1.1 on 2024-12-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_org_org_name_alter_taskfile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
